### ISSUE TITLE
ConfirmReplyController persist the dto

### ISSUE THREAD

**Issue by Federkun** [iltar/blog-articles#3]
[ConfirmReplyData#getComment](https://github.com/iltar/blog-articles/blob/master/src/RethinkingFormDevelopment/ConfirmReplyController.php#L31) returns an instance of CommentData. ATM the action try to persist the dto instead of the entity.

Thanks for the article!

**Comment by iltar** [comment]
Ah nice catch! I forgot to assign the entity when writing the new controller

**Comment by iltar** [comment]
Fixed via https://github.com/iltar/blog-articles/commit/1ff8d03943ae901becbe64a25c3378e8687c59a9, thanks!
